# Base R's Apply Family Demonstration

- **apply** - apply: *matrix row/col -> function -> vector/matrix/array*
- **lapply** - list apply: *vector/list -> function -> list*
- **sapply** - simply apply: *vector/list -> function -> simplified object (vector/matrix) or list*
- **vapply** - verified apply: *vector/list -> function -> defined type (logical/integer/numeric/character) and size*
- **mapply** - multivariate apply: *vectors/lists -> function -> simplified object (vector/matrix) or list*
- **tapply** - tagged apply: *vector and index -> function -> vector*
- **eapply** - environment apply: *environment object -> function -> list*
- **rapply** - recursive apply: *nested list -> function -> nested list*

## Example

Using Meetup.com API data, Chicago R User Group (CRUG) members were downloaded in json files imported into dataframe including member ids, names, bio, joined and visited dates, lat and lon locations, city, state, country, status, and photo URL.

In [1]:
library(jsonlite)

# https://www.meetup.com/meetup_api/docs/2/members/

In [2]:
setwd('/path/to/json_files')

paths <- c("Meetup_JSON/CRUG_members1.json",
           "Meetup_JSON/CRUG_members2.json",
           "Meetup_JSON/CRUG_members3.json",
           "Meetup_JSON/CRUG_members4.json",
           "Meetup_JSON/CRUG_members5.json",
           "Meetup_JSON/CRUG_members6.json",
           "Meetup_JSON/CRUG_members7.json",
           "Meetup_JSON/CRUG_members8.json",
           "Meetup_JSON/CRUG_members9.json",
           "Meetup_JSON/CRUG_members10.json",
           "Meetup_JSON/CRUG_members11.json",
           "Meetup_JSON/CRUG_members12.json",
           "Meetup_JSON/CRUG_members13.json",
           "Meetup_JSON/CRUG_members14.json",
           "Meetup_JSON/CRUG_members15.json")

### Lapply

Passing in paths vector, each json file is imported via an anonymous function with various content extracted into a dataframe to return an equal length list of dataframes. 

Afterwards, all dataframe elements are row binded into one large dataframe complete with the 2,855 Meetup members as of October 9, 2017.

In [3]:
dfList <- lapply(paths, function(i){
  memberdata <- fromJSON(i)
  temp <- data.frame(id = memberdata$results$id,
                     name = memberdata$results$name,
                     bio = memberdata$results$bio,
                     link = memberdata$results$link,
                     lon = memberdata$results$lon,
                     lat = memberdata$results$lat,
                     city = memberdata$results$city,
                     state = memberdata$results$state,   
                     country = memberdata$results$country,
                     visited = memberdata$results$visited,
                     joined = memberdata$results$joined,
                     status = memberdata$results$status,
                     photo = memberdata$results$photo$highres_link,
                     stringsAsFactors = FALSE)
})

In [4]:
df <- do.call(rbind, dfList)

str(df)

'data.frame':	2872 obs. of  13 variables:
 $ id     : int  156081352 109589972 223644803 9646158 24689872 188176390 61182532 9202393 88670002 186530239 ...
 $ name   : chr  "_David___" "A. Bateman" "Aadish Chopra" "Aaron" ...
 $ bio    : chr  NA NA NA NA ...
 $ link   : chr  "http://www.meetup.com/members/156081352" "http://www.meetup.com/members/109589972" "http://www.meetup.com/members/223644803" "http://www.meetup.com/members/9646158" ...
 $ lon    : num  -87.8 -87.6 -87.7 -87.7 -74 ...
 $ lat    : num  42 41.9 41.9 42 40.8 ...
 $ city   : chr  "Park Ridge" "Chicago" "Chicago" "Chicago" ...
 $ state  : chr  "IL" "IL" "IL" "IL" ...
 $ country: chr  "us" "us" "us" "us" ...
 $ visited: num  1.44e+12 1.38e+12 1.51e+12 1.36e+12 1.44e+12 ...
 $ joined : num  1.43e+12 1.38e+12 1.50e+12 1.36e+12 1.43e+12 ...
 $ status : chr  "active" "active" "active" "active" ...
 $ photo  : chr  "https://secure.meetupstatic.com/photos/member/5/5/6/3/highres_249141859.jpeg" "https://secure.meetupstatic.com/photos/member/b/d/1/2/highres_143988402.jpeg" NA "https://secure.meetupstatic.com/photos/member/5/2/a/4/highres_12501156.jpeg" ...

In [5]:
head(df, 10)

   id        name
1  156081352 _David___
2  109589972 A. Bateman
3  223644803 Aadish Chopra
4    9646158 Aaron
5   24689872 Aaron
6  188176390 Aaron An
7   61182532 Aaron Foss
8    9202393 Aaron Goldenberg
9   88670002 Aaron Howard
10 186530239 Aaron Katch
   bio
1  NA
2  NA
3  NA
4  NA
5  NA
6  NA
7  NA
8  NA
9  I received my PhD in Biology from Georgetown University, and now I am an Instructor at NEIU.
10 NA
   link                                    lon    lat   city       state
1  http://www.meetup.com/members/156081352 -87.83 41.97 Park Ridge IL
2  http://www.meetup.com/members/109589972 -87.64 41.90 Chicago    IL
3  http://www.meetup.com/members/223644803 -87.69 41.88 Chicago    IL
4  http://www.meetup.com/members/9646158   -87.66 41.99 Chicago    IL
5  http://www.meetup.com/members/24689872  -73.99 40.76 New York   NY
6  http://www.meetup.com/members/188176390 -87.63 41.89 Chicago    IL
7  http://www.meetup.com/members/61182532  -87.64 41.88 Chicago    IL
8  http://www.meetup.com/members/9202393   -73.99 40.75 New York   NY
9  http://www.meetup.com/members/88670002  -87.64 41.88 Chicago    IL
10 http://www.meetup.com/members/186530239 -87.92 43.04 Milwaukee  WI
   country visited      joined       status
1  us      1.437896e+12 1.428087e+12 active
2  us      1.384974e+12 1.378224e+12 active
3  us      1.514492e+12 1.504635e+12 active
4  us      1.358789e+12 1.357092e+12 active
5  us      1.444925e+12 1.429748e+12 active
6  us      1.433356e+12 1.433356e+12 active
7  us      1.468464e+12 1.346859e+12 active
8  us      1.466677e+12 1.431702e+12 active
9  us      1.365647e+12 1.365647e+12 active
10 us      1.463204e+12 1.435240e+12 active
   photo
1  https://secure.meetupstatic.com/photos/member/5/5/6/3/highres_249141859.jpeg
2  https://secure.meetupstatic.com/photos/member/b/d/1/2/highres_143988402.jpeg
3  NA
4  https://secure.meetupstatic.com/photos/member/5/2/a/4/highres_12501156.jpeg
5  https://secure.meetupstatic.com/photos/member/7/8/0/2/highres_102570722.jpeg
6  https://secure.meetupstatic.com/photos/member/3/9/2/b/highres_246734635.jpeg
7  NA
8  https://secure.meetupstatic.com/photos/member/8/9/0/a/highres_95495082.jpeg
9  NA
10 https://secure.meetupstatic.com/photos/member/7/8/6/2/highres_247350818.jpeg

In [6]:
# CRUG ORGANIZERS
df[grep("adam g|Justin Shea|Charlotte F|Irena|Paul Teetor|Troy H|Joe Cursio|Gene L", df$name),]

     id        name
35   145615862 adam ginensky
475  110212102 Charlotte Frei
914    4570669 Gene Leynes
1060 213068098 Irena Kaplan-Cohen
1254   6498432 Joe Cursio
1416  69630512 Justin Shea
2092  11836216 Paul Teetor
2677 138973202 Troy Hernandez
     bio
35   I use R extensively  in my current practice as a consultant. I've been an instructor at both University of Chicago and Northwestern where I've used R in teaching various classes.  I am a reformed floor trader with a Ph.d. in mathematics.
475  NA
914  I'm currently a data scientist at the City of Chicago. I first used R in 2006, but I didn't really enjoy R until about 2009. I began my data science career as an actuarial consultant in 1999.  I have many interests, and two children.
1060 NA
1254 at IIT Stuart School of Business, former Masters in Finance student, PhD student, adjunct professor and Associate Director for the Center for Corporate Performance
1416 Data Science consultant and Economics department faculty member at Roosevelt University. I discovered R to better model actively managed portfolios  of commodity futures, which led to an affinity for the  open source data community.
2092 Quantitative developer in securities trading and portfolio management. A geek with some dimension.
2677 I have a PhD in Statistics from UIC. I am an open source technical evangelist at IBM.
     link                                    lon    lat   city    state country
35   http://www.meetup.com/members/145615862 -87.64 41.88 Chicago IL    us
475  http://www.meetup.com/members/110212102 -87.70 41.94 Chicago IL    us
914  http://www.meetup.com/members/4570669   -87.67 41.90 Chicago IL    us
1060 http://www.meetup.com/members/213068098 -87.64 41.88 Chicago IL    us
1254 http://www.meetup.com/members/6498432   -87.64 41.90 Chicago IL    us
1416 http://www.meetup.com/members/69630512  -87.64 41.88 Chicago IL    us
2092 http://www.meetup.com/members/11836216  -87.64 41.88 Chicago IL    us
2677 http://www.meetup.com/members/138973202 -87.66 41.85 Chicago IL    us
     visited      joined       status
35   1.516418e+12 1.399508e+12 active
475  1.516627e+12 1.378752e+12 active
914  1.508512e+12 1.271602e+12 active
1060 1.516715e+12 1.474047e+12 active
1254 1.516995e+12 1.272382e+12 active
1416 1.516917e+12 1.352877e+12 active
2092 1.512735e+12 1.270601e+12 active
2677 1.516738e+12 1.395763e+12 active
     photo
35   https://secure.meetupstatic.com/photos/member/3/0/7/2/highres_196152402.jpeg
475  https://secure.meetupstatic.com/photos/member/8/2/7/a/highres_197253402.jpeg
914  https://secure.meetupstatic.com/photos/member/8/d/f/6/highres_55236342.jpeg
1060 https://secure.meetupstatic.com/photos/member/6/c/5/2/highres_260187730.jpeg
1254 NA
1416 https://secure.meetupstatic.com/photos/member/5/c/0/7/highres_262523559.jpeg
2092 https://secure.meetupstatic.com/photos/member/1/a/b/4/highres_9366836.jpeg
2677 https://secure.meetupstatic.com/photos/member/b/1/2/8/highres_188205352.jpeg

In [7]:
# RSVP EVENT MEMBERS
event_members <- fromJSON("Meetup_JSON/CRUG_eventmembers.json")

event_members_df <- data.frame(
  member_id = event_members$member$id,
  member_name = event_members$member$name,
  host = event_members$member$event_context$host,
  role = event_members$member$role,
  response = event_members$response,
  bio = event_members$member$bio,
  photo = event_members$member$photo$highres_link,
  stringsAsFactors = FALSE
)

In [8]:
head(event_members_df, 10)

   member_id member_name   host  role        response
1  223644803 Aadish Chopra FALSE NA          yes
2  155209922 AC            FALSE NA          yes
3  145615862 adam ginensky FALSE coorganizer yes
4    4347699 Alex Nelson   FALSE NA          yes
5  207877301 Alex Pax      FALSE NA          yes
6   73936482 Alex Welch    FALSE NA          no
7  229115380 Amanda Dobbyn FALSE NA          yes
8   34840632 Amy           FALSE NA          yes
9  196816275 Andrew Nguyen FALSE NA          yes
10 183838572 Andrew Olson  FALSE NA          yes
   bio
1  NA
2  NA
3  I use R extensively  in my current practice as a consultant. I've been an instructor at both University of Chicago and Northwestern where I've used R in teaching various classes.  I am a reformed floor trader with a Ph.d. in mathematics.
4  NA
5  NA
6  NA
7  NA
8  Loyal R user :)
9  NA
10 NA
   photo
1  https://secure.meetupstatic.com/photos/member/2/9/a/1/highres_270370657.jpeg
2  https://secure.meetupstatic.com/photos/member/b/8/c/1/highres_258347297.jpeg
3  https://secure.meetupstatic.com/photos/member/3/0/7/2/highres_196152402.jpeg
4  https://secure.meetupstatic.com/photos/member/2/8/b/8/highres_241630424.jpeg
5  https://secure.meetupstatic.com/photos/member/e/6/a/7/highres_257819047.jpeg
6  NA
7  https://secure.meetupstatic.com/photos/member/2/3/8/b/highres_267549099.jpeg
8  https://secure.meetupstatic.com/photos/member/b/8/4/e/highres_228827182.jpeg
9  https://secure.meetupstatic.com/photos/member/7/9/a/5/highres_252091141.jpeg
10 https://secure.meetupstatic.com/photos/member/f/4/e/highres_243183918.jpeg

In [9]:
subset(event_members_df, host == TRUE | role == 'organizer' | role == 'coorganizer')

    member_id member_name        host  role        response
3   145615862 adam ginensky      FALSE coorganizer yes
21  110212102 Charlotte Frei      TRUE coorganizer yes
52  213068098 Irena Kaplan-Cohen FALSE coorganizer yes
60    6498432 Joe Cursio          TRUE coorganizer yes
66   69630512 Justin Shea        FALSE organizer   yes
101 186806194 Raj                FALSE coorganizer no
129 138973202 Troy Hernandez     FALSE coorganizer yes
    bio
3   I use R extensively  in my current practice as a consultant. I've been an instructor at both University of Chicago and Northwestern where I've used R in teaching various classes.  I am a reformed floor trader with a Ph.d. in mathematics.
21  NA
52  NA
60  at IIT Stuart School of Business, former Masters in Finance student, PhD student, adjunct professor and Associate Director for the Center for Corporate Performance
66  Data Science consultant and Economics department faculty member at Roosevelt University. I discovered R to better model actively managed portfolios  of commodity futures, which led to an affinity for the  open source data community.
101 NA
129 I have a PhD in Statistics from UIC. I am an open source technical evangelist at IBM.
    photo
3   https://secure.meetupstatic.com/photos/member/3/0/7/2/highres_196152402.jpeg
21  https://secure.meetupstatic.com/photos/member/8/2/7/a/highres_197253402.jpeg
52  https://secure.meetupstatic.com/photos/member/6/c/5/2/highres_260187730.jpeg
60  https://secure.meetupstatic.com/photos/member/5/f/3/a/highres_257904378.jpeg
66  https://secure.meetupstatic.com/photos/member/5/c/0/7/highres_262523559.jpeg
101 https://secure.meetupstatic.com/photos/member/c/d/4/f/highres_245812559.jpeg
129 https://secure.meetupstatic.com/photos/member/b/1/2/8/highres_188205352.jpeg

In [10]:
# MERGE FOR EVENT MEMBER INDICATOR
df <- merge(df, event_members_df[c("member_id", "response")], by.x="id", by.y="member_id", all.x=TRUE, stringsAsFactors=FALSE)

str(df)

'data.frame':	2872 obs. of  14 variables:
 $ id      : int  30175 38566 126040 145317 152870 224762 391103 462692 466031 606021 ...
 $ name    : chr  "Dave Lewis" "jhe1" "Bill M" "ElAleph" ...
 $ bio     : chr  NA NA "Grad student at UChicago." NA ...
 $ link    : chr  "http://www.meetup.com/members/30175" "http://www.meetup.com/members/38566" "http://www.meetup.com/members/126040" "http://www.meetup.com/members/145317" ...
 $ lon     : num  -96.8 -87.8 -87.6 -87.6 -87.6 ...
 $ lat     : num  33 41.9 41.9 41.9 41.9 ...
 $ city    : chr  "Addison" "Chicago" "Chicago" "Chicago" ...
 $ state   : chr  "TX" "IL" "IL" "IL" ...
 $ country : chr  "us" "us" "us" "us" ...
 $ visited : num  1.46e+12 1.28e+12 1.49e+12 1.51e+12 1.43e+12 ...
 $ joined  : num  1.45e+12 1.28e+12 1.39e+12 1.44e+12 1.43e+12 ...
 $ status  : chr  "active" "active" "active" "active" ...
 $ photo   : chr  "https://secure.meetupstatic.com/photos/member/5/0/f/a/highres_253940730.jpeg" NA "https://secure.meetupstatic.com/photos/member/7/8/5/highres_259801925.jpeg" "https://secure.meetupstatic.com/photos/member/c/f/a/2/highres_259553154.jpeg" ...
 $ response: chr  NA NA NA NA ...

In [11]:
# OPEN ORGANIZER PHOTO LINKS

# UPDATE JOE C PHOTO
df[df$id == 6498432, "photo"] <- 'https://secure.meetupstatic.com/photos/member/d/0/e/a/member_180473482.jpeg'

tryCatch(sapply(df[grep("adam g|Justin Shea|Charlotte F|Irena|Paul Teetor|Troy H|Joe Cursio|Gene L", df$name), "photo"], 
                browseURL), error = function(e) return(NA))

 https://secure.meetupstatic.com/photos/member/8/d/f/6/highres_55236342.jpeg
                                                                           0
 https://secure.meetupstatic.com/photos/member/d/0/e/a/member_180473482.jpeg
                                                                           0
  https://secure.meetupstatic.com/photos/member/1/a/b/4/highres_9366836.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/5/c/0/7/highres_262523559.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/8/2/7/a/highres_197253402.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/b/1/2/8/highres_188205352.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/3/0/7/2/highres_196152402.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/6/c/5/2/highres_260187730.jpeg
                                                                           0

In [12]:
# OPEN RANDOM 5 EVENT MEMBERS LINKS
tryCatch(sapply(as.character(event_members_df[sample(nrow(event_members_df), 7), "photo"]), 
                browseURL), error = function(e) return(NA))

https://secure.meetupstatic.com/photos/member/6/1/a/5/highres_271884997.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/6/a/5/c/highres_272787228.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/a/4/3/5/highres_271182037.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/c/d/4/f/highres_245812559.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/6/0/5/5/highres_241404661.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/d/3/d/1/highres_246114225.jpeg
                                                                           0
https://secure.meetupstatic.com/photos/member/1/7/0/b/highres_270305899.jpeg
                                                                           0

### Apply

Using apply, we join all row values into one string for first 5 rows.

In [13]:
apply(df[which(df$response == "yes"), c("id", "name", "link", "city", "state", "country", "bio")], 1, 
      function(g) paste(g, collapse=", "))[1:5]

                                                                                                                                                                                                          28
"  1981292, erica, http://www.meetup.com/members/1981292, Chicago, IL, us, Hi, my name is Erica and I have been working with data for over 10 years. However, i am just starting to get into data analytics"
                                                                                                                                                                                                          33
                                                                                                                            "  2299745, Temi, http://www.meetup.com/members/2299745, Naperville, IL, us, NA"
                                                                                                                                                                                                          51
                                                                                                           "  2807240, Ravi, http://www.meetup.com/members/2807240, Evanston, IL, us, Senior Data Scientist"
                                                                                                                                                                                                          57
                                                                                                                   "  2872910, Crystal Campbell, http://www.meetup.com/members/2872910, Chicago, IL, us, NA"
                                                                                                                                                                                                          81
                                                                                                                        "  4035068, Vijay Jakka, http://www.meetup.com/members/4035068, Chicago, IL, us, NA"

### Sapply

The joined and visited time stamps in epoch time integers are converted to dates. And with sapply, we create rankings of members according to time.

In [13]:
df$joined <- as.POSIXct(df$joined/1000, origin="1970-01-01")

df$joined_rank <- sapply(df$joined, function(i) sum(df$joined <= i))

In [15]:
df <- with(df, df[order(joined_rank),])

head(df[,c("name", "joined_rank", "status", "joined")], 10)

    name              joined_rank status joined
282 JD Long            1          active 2010-04-05 14:04:24
283 Jeffrey Ryan       2          active 2010-04-05 15:52:23
284 Douglas J. Hobbs   3          active 2010-04-05 15:57:13
165 Mark               4          active 2010-04-05 16:01:38
285 Dirk Eddelbuettel  5          active 2010-04-05 16:11:43
286 Joshua Ulrich      6          active 2010-04-05 16:15:03
234 Brian Peterson     7          active 2010-04-05 16:42:57
287 Zinnya del Villar  8          active 2010-04-05 17:22:24
217 Marck Vaisman      9          active 2010-04-05 23:11:32
157 David Smith       10          active 2010-04-06 11:05:30

In [16]:
head(df[which(df$response == "yes"), c("name", "joined_rank", "status", "joined")], 10)

     name                 joined_rank status joined
288  Sameer                11         active 2010-04-06 13:23:36
115  Joe Cursio            39         active 2010-04-27 10:20:47
538  G Gershuny           150         active 2011-05-25 00:27:48
632  Tom Corrigan         198         active 2011-11-10 08:11:26
704  J Anthony            258         active 2012-02-24 05:47:47
508  Cory Mollet          273         active 2012-03-16 18:57:24
760  Joseph Day           306         active 2012-04-11 15:29:59
668  Arjun Krishnamoorthi 510         active 2012-11-02 07:44:07
1018 Todd Mattson         518         active 2012-11-08 13:43:02
1026 Justin Shea          526         active 2012-11-14 01:17:25

In [17]:
# CRUG ORGANIZERS
df[grep("adam g|Justin Shea|Charlotte F|Irena|Paul Teetor|Troy H|Joe Cursio|Gene L", df$name),
   c("name", "joined_rank", "status", "joined")]

     name               joined_rank status joined
295  Paul Teetor          21        active 2010-04-06 19:51:33
93   Gene Leynes          36        active 2010-04-18 09:41:32
115  Joe Cursio           39        active 2010-04-27 10:20:47
1026 Justin Shea         526        active 2012-11-14 01:17:25
1383 Charlotte Frei      832        active 2013-09-09 13:39:23
1567 Troy Hernandez      972        active 2014-03-25 11:01:18
1610 adam ginensky      1044        active 2014-05-07 19:20:42
2415 Irena Kaplan-Cohen 2055        active 2016-09-16 12:23:53

###  Vapply

And with vapply, we create rankings of members according to time, specifying the return of integer at length of 1 (i.e., atomic vector).

In [18]:
df$visited <- as.POSIXct(df$visited/1000, origin="1970-01-01")

df$visited_rank <- vapply(df$visited, function(i) sum(df$visited >= i), integer(1))

In [19]:
df <- with(df, df[order(visited_rank),])

head(df[which(df$response == "yes"), c("name", "visited_rank", "status", "visited")], 10)

     name             visited_rank status visited
277  Parfait           1           active 2018-01-26 19:58:33
2766 Emily Liu         2           active 2018-01-26 19:58:20
2124 Masi              3           active 2018-01-26 19:45:15
2859 Prema             4           active 2018-01-26 19:43:07
106  russ conte        6           active 2018-01-26 18:59:47
2806 vitastata sharma  7           active 2018-01-26 18:59:17
2872 Pavan Palve       8           active 2018-01-26 18:53:30
2720 Chase Clark       9           active 2018-01-26 18:40:14
2861 Yang He          11           active 2018-01-26 17:21:47
2732 Eric Swanson     12           active 2018-01-26 17:09:38

In [20]:
# ORGANIZERS
df[grep('adam g|Justin Shea|Irena|Charlotte F|Paul Teetor|Troy H|Joe Cursio|Gene L', df$name),
   c("name", "joined", "joined_rank", "visited", "visited_rank"),]

     name               joined              joined_rank visited
115  Joe Cursio         2010-04-27 10:20:47   39        2018-01-26 13:23:39
1026 Justin Shea        2012-11-14 01:17:25  526        2018-01-25 15:56:34
1567 Troy Hernandez     2014-03-25 11:01:18  972        2018-01-23 14:00:09
2415 Irena Kaplan-Cohen 2016-09-16 12:23:53 2055        2018-01-23 07:48:52
1383 Charlotte Frei     2013-09-09 13:39:23  832        2018-01-22 07:12:19
1610 adam ginensky      2014-05-07 19:20:42 1044        2018-01-19 21:21:25
295  Paul Teetor        2010-04-06 19:51:33   21        2017-12-08 06:16:42
93   Gene Leynes        2010-04-18 09:41:32   36        2017-10-20 10:03:36
     visited_rank
115   24
1026  53
1567  77
2415  84
1383  96
1610 120
295  262
93   534

### Mapply

Using lat and lon fields, we calculate the distance of each member from Cubs Wrigley Field (neighborhood due to two-digit coordinates). 

Using the Haversine distance formula. we pass in two inputs using mapply for lat and lon coordinates.

In [21]:
haversinef <- function(lon1, lat1) {
  R <- 6371 # Earth mean radius [km]
  kmconv <- 0.621371
  
  lat1Radians <- (lat1 / 180) * (4 * atan(1))
  lon1Radians <- (lon1 / 180) * (4 * atan(1))
  lat2Radians <- (41.9484 / 180) * (4 * atan(1))
  lon2Radians <- (-87.6553 / 180) * (4 * atan(1))
  
  AsinBase <- sin(sqrt(sin((lat1Radians - lat2Radians) / 2) ^ 2 + cos(lat1Radians) * cos(lat2Radians) * sin((lon1Radians - lon2Radians) / 2) ^ 2))
  DerivedAsin <- (AsinBase / sqrt(-AsinBase * AsinBase + 1))
  
  return (round(2 * DerivedAsin * (R * kmconv), 2))
  
}

df$WrigleyDistance <- mapply(haversinef, df$lon+0.0068, df$lat+0.0037)

In [22]:
df <- with(df, df[order(df$WrigleyDistance),])

head(df[which(df$response == "yes"), c("name", "lat", "lon", "city", "state", "country", "WrigleyDistance")], 10)

     name            lat   lon    city    state country WrigleyDistance
2327 Alex Pax        41.94 -87.65 Chicago IL    us      0.70
2125 Hannah          41.94 -87.65 Chicago IL    us      0.70
1462 stacie          41.96 -87.66 Chicago IL    us      1.06
2659 Raunak Pednekar 41.93 -87.64 Chicago IL    us      1.52
1363 Matthew         41.97 -87.67 Chicago IL    us      1.79
28   erica           41.92 -87.65 Chicago IL    us      1.82
1383 Charlotte Frei  41.94 -87.70 Chicago IL    us      1.97
2660 Amanda Dobbyn   41.94 -87.70 Chicago IL    us      1.97
1895 Keith Hultman   41.94 -87.70 Chicago IL    us      1.97
1674 AC              41.97 -87.70 Chicago IL    us      2.62

### Map(), wrapper to mapply for list or non-simplified output

In [23]:
map_list <- Map(haversinef, df$lon+0.0068, df$lat+0.0037)

str(map_list[1:10])

List of 10
 $ : num 0.34
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7
 $ : num 0.7

In [24]:
tail(df[, c("name", "lat", "lon", "city", "state", "country", "WrigleyDistance")], 10)

     name             lat    lon    city         state country WrigleyDistance
1357 Nick Kennedy     -33.87 151.21 Sydney       NA    au      10391.65
158  Jeff Fung        -33.94 151.18 Sydney       NA    au      10395.70
1925 KN Loo             3.16 101.71 Kuala Lumpur NA    my      10415.43
1872 Hieu Tran          1.33 103.95 Singapore    NA    sg      10515.33
85   Whiz               1.30 103.85 Singapore    NA    sg      10518.99
1371 Aislinn            1.30 103.85 Singapore    NA    sg      10518.99
596  Sankalp Upadhyay   1.30 103.85 Singapore    NA    sg      10518.99
1374 Brian            -35.31 149.13 Canberra     NA    au      10550.74
481  John Persico     -37.81 144.96 Melbourne    NA    au      10836.64
756  Wil              -37.81 144.96 Melbourne    NA    au      10836.64

In [25]:
tail(df[which(df$response == "yes"), c("name", "lat", "lon", "city", "state", "country", "WrigleyDistance")], 10)

     name          lat   lon     city                 state country
1908 Wei Zhao      41.77  -88.15 Naperville           IL    us
1447 Tania Moulik  41.76  -88.24 Aurora               IL    us
2855 Prethi Vennam 42.37  -87.93 Gurnee               IL    us
1871 Andrew Olson  42.96  -87.99 Milwaukee            WI    us
2295 Daphne Smith  38.26  -85.50 Louisville           KY    us
1449 Sean Baron    40.15  -74.98 Feasterville Trevose PA    us
2631 ASJ           47.68 -122.12 Redmond              WA    us
1424 April         33.65 -117.82 Irvine               CA    us
1405 Douglas       34.08 -118.26 Los Angeles          CA    us
1821 Nikita Maloo  26.34   90.66 Abhayapuri           NA    in
     WrigleyDistance
1908   27.86
1447   32.36
2855   32.43
1871   72.12
2295  279.08
1449  672.48
2631 1732.93
1424 1746.36
1405 1755.10
1821 8614.32

In [26]:
# ORGANIZERS
df[grep('adam g|Justin Shea|Irena|Charlotte F|Paul Teetor|Troy H|Joe Cursio|Gene L', df$name),
        c("name", "lat", "lon", "city", "state", "country", "WrigleyDistance"),]

     name               lat   lon    city    state country WrigleyDistance
1383 Charlotte Frei     41.94 -87.70 Chicago IL    us      1.97
93   Gene Leynes        41.90 -87.67 Chicago IL    us      3.12
115  Joe Cursio         41.90 -87.64 Chicago IL    us      3.29
1026 Justin Shea        41.88 -87.64 Chicago IL    us      4.61
2415 Irena Kaplan-Cohen 41.88 -87.64 Chicago IL    us      4.61
1610 adam ginensky      41.88 -87.64 Chicago IL    us      4.61
295  Paul Teetor        41.88 -87.64 Chicago IL    us      4.61
1567 Troy Hernandez     41.85 -87.66 Chicago IL    us      6.54

### Tapply

Using tapply, we run aggregates across various subsets.

In [27]:
citycount <- tapply(df$id, df$city, length)

citycount[order(-citycount)]

             Chicago             New York             Evanston
                2067                   38                   36
       San Francisco           Naperville              Seattle
                  32                   29                   17
            Oak Park    Arlington Heights           Schaumburg
                  16                   15                   15
              Aurora             Palatine        Buffalo Grove
                  12                   11                   10
             Madison            Milwaukee           Washington
                  10                   10                   10
            Glenview      Hoffman Estates            Hyderabad
                   9                    7                    7
          Northbrook            Oak Brook             Wheeling
                   7                    7                    7
           Deerfield          Forest Park           Park Ridge
                   6                    6                    6
           Sunnyvale              Wheaton           Cincinnati
                   6                    6                    5
         Des Plaines        Downers Grove           Glen Ellyn
                   5                    5                    5
         Los Angeles       Mount Prospect             San Jose
                   5                    5                    5
            Wilmette            Ann Arbor            Bangalore
                   5                    4                    4
              Boston            Cambridge               Gurnee
                   4                    4                    4
           La Grange          Lake Forest         Lincolnshire
                   4                    4                    4
               Lisle              Lombard              Oakland
                   4                    4                    4
          Pittsburgh           Plainfield           Romeoville
                   4                    4                    4
           San Mateo            Singapore               Skokie
                   4                    4                    4
             Toronto              Atlanta               Austin
                   4                    3                    3
         Bloomington          Bolingbrook             Brooklyn
                   3                    3                    3
           Champaign             Columbus    Elk Grove Village
                   3                    3                    3
            Elmhurst               Geneva         Indianapolis
                   3                    3                    3
          Lake Bluff           Lake Villa         Libertyville
                   3                    3                    3
            Lockport               London          Minneapolis
                   3                    3                    3
           Mundelein           Oak Forest            Palo Alto
                   3                    3                    3
            Portland         Redwood City          Saint Louis
                   3                    3                    3
         Tinley Park             Westmont           Abhayapuri
                   3                    3                    2
              Albany            Algonquin              Arcadia
                   2                    2                    2
             Batavia             Bellevue             Berkeley
                   2                    2                    2
              Berlin               Berwyn         Bloomingdale
                   2                    2                    2
           Charlotte      Chicago Heights              Coppell
                   2                    2                    2
        Crystal Lake               Dekalb               Denver
                   2                    2                    2
              Durham           Farmington      Fort Lauderdale
                   2                    2                    2
            Franklin         Grand Rapids         Hanover Park
                   2                    2                    2
       Highland Park             Hinsdale               Itasca
                   2                    2                    2
         Lincolnwood            Melbourne          Morrisville
                   2                    2                    2
       Mountain View            Nashville               Newark
                   2                    2                    2
              Normal        North Chicago             Pasadena
                   2                    2                    2
              Peoria         Philadelphia              Potomac
                   2                    2                    2
        River Forest            Rochester      Rolling Meadows
                   2                    2                    2
         Santa Clara            São Paulo             Stanford
                   2                    2                    2
            Sycamore               Sydney               Taipei
                   2                    2                    2
          Valparaiso          Westchester White River Junction
                   2                    2                    2
             Addison            Amsterdam              Ashburn
                   1                    1                    1
            Auckland                 Avon              Bangkok
                   1                    1                    1
           Barcelona               Barnet           Barrington
                   1                    1                    1
            Bartlett          Bentonville             Bethesda
                   1                    1                    1
          Bettendorf        Beverly Hills           Blacksburg
                   1                    1                    1
             Bothell             Brasília           Bratislava
                   1                    1                    1
          Bridgeview           Brookfield           Brownsburg
                   1                    1                    1
            Brussels           Burlingame             Canberra
                   1                    1                    1
              Canton         Carol Stream                 Cary
                   1                    1                    1
            Chandler          Chapel Hill              Chennai
                   1                    1                    1
         Cherry Hill         Chesterfield        Chicago Ridge
                   1                    1                    1
          Chippenham          Chula Vista               Cicero
                   1                    1                    1
           Cleveland     Clinton Township         Collinsville
                   1                    1                    1
         Crown Point              Cumming             Danville
                   1                    1                    1
              Darien                Delhi              Del Mar
                   1                    1                    1
          Des Moines              Detroit               Draper
                   1                    1                    1
               Dubai         East Lansing         Eden Prairie
                   1                    1                    1
              Edison                Elgin         Elmwood Park
                   1                    1                    1
           Encinitas Feasterville Trevose              Fishers
                   1                    1                    1
           Flossmoor         Fort Collins            Fort Mill
                   1                    1                    1
     Fox River Grove                  FPO            Frankfort
                   1                    1                    1
                Gary               Getafe              Glencoe
                   1                    1                    1
      Grand Junction              Granger            Grayslake
                   1                    1                    1
       Grosse Pointe             Hangzhou          Hazel Crest
                   1                    1                    1
             Herndon              Hingham           Homer Glen
                   1                    1                    1
           Hong Kong              Houston          Hyattsville
                   1                    1                    1
              Icheon           Indaiatuba               Irvine
                   1                    1                    1
         Jersey City              Kenosha            Knoxville
                   1                    1                    1
        Kuala Lumpur       La Grange Park          Lake Zurich
                   1                    1                    1
             La Mesa              Lansing            Las Vegas
                   1                    1                    1
           Lexington            Ljubljana           Louisville
                   1                    1                    1
          Luxembourg       Machesney Park               Madrid
                   1                    1                    1
             Malvern               Manaus            Manhattan
                   1                    1                    1
           Maplewood              McHenry              Mc Lean
                   1                    1                    1
             Medford           Menlo Park                 Mesa
                   1                    1                    1
          Middletown           Midlothian              Minooka
                   1                    1                    1
           Mishawaka    Mississippi State               Mokena
                   1                    1                    1
         Mooresville            Mount Joy               Mumbai
                   1                    1                    1
           Nederland        New Brunswick            New Haven
                   1                    1                    1
           New Lenox          New Orleans        Newport Beach
                   1                    1                    1
    Newton Highlands          Northampton       North Royalton
                   1                    1                    1
          Notre Dame                 Novi             O Fallon
                   1                    1                    1
      Olympia Fields                Omaha             Pacifica
                   1                    1                    1
               Paris           Piscataway                Plano
                   1                    1                    1
    Pleasant Prairie               Prague     Prospect Heights
                   1                    1                    1
                Pune              Raleigh              Redmond
                   1                    1                    1
              Rennes               Reston            Riverside
                   1                    1                    1
             Roanoke              Rocklin            Rockville
                   1                    1                    1
          Rolesville                 Roma              Roselle
                   1                    1                    1
          Round Lake        Saint Charles         San Clemente
                   1                    1                    1
           San Diego           San Marino         Santa Monica
                   1                    1                    1
            Sarasota          Scarborough            Scarsdale
                   1                    1                    1
          Scottsdale           Sebastopol                Seoul
                   1                    1                    1
            Shanghai             Shenzhen           South Bend
                   1                    1                    1
           Southlake          Springfield             Stamford
                   1                    1                    1
            Tambaram                Tampa                Tempe
                   1                    1                    1
               Tokyo              Trieste         Two Mile Ash
                   1                    1                    1
               Union               Urbana            Urbandale
                   1                    1                    1
           Vancouver         Vernon Hills           Villa Park
                   1                    1                    1
              Warsaw             Waukegan             Waukesha
                   1                    1                    1
        West Chicago         White Plains          Willowbrook
                   1                    1                    1
          Wilmington               Zürich
                   1                    1

In [28]:
joinedyearcount <- tapply(df$id, format(df$joined, "%Y"), length)

joinedyearcount[order(-joinedyearcount)]

2017 2015 2016 2014 2012 2013 2011 2010 2018
 670  461  411  394  340  330  113  107   46

### by(), object-oriented wrapper to tapply

In [29]:
bylist <- by(df, df$city, FUN=function(i) i)

head(bylist$Chicago, 5)
head(bylist$`New York`, 5)
head(bylist$`San Francisco`, 5)
head(bylist$Seattle, 5)
head(bylist$Milwaukee, 5)

     id        name
1965 186105646 Joe Bringley
133    7631068 Igor Veksler
157    8481017 David Smith
2327 207877301 Alex Pax
2125 194357394 Hannah
     bio
1965 NA
133  big fan of the R language & the R community
157  I'm the Chief Community Officer for Revolution Analytics, based in Chicago.
2327 NA
2125 NA
     link                                    lon    lat   city    state country
1965 http://www.meetup.com/members/186105646 -87.66 41.94 Chicago IL    us
133  http://www.meetup.com/members/7631068   -87.65 41.94 Chicago IL    us
157  http://www.meetup.com/members/8481017   -87.65 41.94 Chicago IL    us
2327 http://www.meetup.com/members/207877301 -87.65 41.94 Chicago IL    us
2125 http://www.meetup.com/members/194357394 -87.65 41.94 Chicago IL    us
     visited             joined              status
1965 2017-11-15 17:37:34 2017-11-15 17:37:34 active
133  2018-01-26 09:15:51 2012-08-20 13:18:57 active
157  2018-01-26 08:38:09 2010-04-06 11:05:30 active
2327 2018-01-23 08:32:35 2017-02-15 21:52:42 active
2125 2018-01-17 23:58:15 2017-04-29 18:12:15 active
     photo
1965 https://secure.meetupstatic.com/photos/member/3/b/1/f/highres_245295135.jpeg
133  NA
157  https://secure.meetupstatic.com/photos/member/1/5/6/0/highres_237005472.jpeg
2327 https://secure.meetupstatic.com/photos/member/e/6/a/7/highres_257819047.jpeg
2125 https://secure.meetupstatic.com/photos/member/7/7/d/9/highres_266490681.jpeg
     response joined_rank visited_rank WrigleyDistance
1965 NA       2785        334          0.34
133  NA        425         36          0.70
157  no         10         39          0.70
2327 yes      2250         83          0.70
2125 yes      2377        134          0.70

     id        name           bio
2174 196693207 joe g k        NA
398   12988232 Kirk Mettler   NA
234   10622236 Brian Peterson "I'm one of those finance geeks..."
642   31797242 Jack DiMassimo NA
1066  73231222 Jennifer Joo   NA
     link                                    lon    lat   city     state
2174 http://www.meetup.com/members/196693207 -74.01 40.73 New York NY
398  http://www.meetup.com/members/12988232  -74.01 40.73 New York NY
234  http://www.meetup.com/members/10622236  -74.01 40.73 New York NY
642  http://www.meetup.com/members/31797242  -74.00 40.74 New York NY
1066 http://www.meetup.com/members/73231222  -74.01 40.70 New York NY
     country visited             joined              status
2174 us      2017-09-07 16:18:32 2017-05-08 18:35:02 active
398  us      2016-05-19 07:26:32 2011-05-23 10:17:32 active
234  us      2014-10-02 19:06:50 2010-04-05 16:42:57 active
642  us      2015-04-04 23:07:53 2011-11-29 23:23:58 active
1066 us      2016-10-24 14:40:18 2015-01-20 00:06:07 active
     photo
2174 NA
398  https://secure.meetupstatic.com/photos/member/6/4/c/b/highres_12025803.jpeg
234  https://secure.meetupstatic.com/photos/member/d/b/6/1/highres_9356161.jpeg
642  https://secure.meetupstatic.com/photos/member/c/a/c/b/highres_245091915.jpeg
1066 https://secure.meetupstatic.com/photos/member/f/c/9/highres_247744041.jpeg
     response joined_rank visited_rank WrigleyDistance
2174 NA       2390         660         713.34
398  NA        149        1657         713.34
234  NA          7        2285         713.34
642  NA        211        2050         713.72
1066 NA       1308        1362         713.75

     id        name
1559 137284262 Ethan Zou
352   12468940 Ben Duffy
1488 129837032 melody
2193 198114965 Carlos Sessa
1457 123186892 Josephine Wang
     bio
1559 First year analyst at TransUnion, shifting from SAS to R
352  NA
1488 NA
2193 NA
1457 Director of Customer Experience, 0xdata
     link                                    lon     lat   city          state
1559 http://www.meetup.com/members/137284262 -122.40 37.80 San Francisco CA
352  http://www.meetup.com/members/12468940  -122.39 37.77 San Francisco CA
1488 http://www.meetup.com/members/129837032 -122.39 37.77 San Francisco CA
2193 http://www.meetup.com/members/198114965 -122.40 37.79 San Francisco CA
1457 http://www.meetup.com/members/123186892 -122.40 37.79 San Francisco CA
     country visited             joined              status
1559 us      2014-04-05 09:48:51 2014-03-14 15:29:49 active
352  us      2015-05-05 09:53:56 2012-10-02 11:32:08 active
1488 us      2014-10-11 16:18:26 2014-10-11 16:18:26 active
2193 us      2018-01-17 09:20:26 2018-01-17 09:20:26 active
1457 us      2017-08-22 15:29:48 2014-04-30 16:53:19 active
     photo
1559 https://secure.meetupstatic.com/photos/member/a/d/e/5/highres_246944517.jpeg
352  NA
1488 https://secure.meetupstatic.com/photos/member/1/8/4/e/highres_172626222.jpeg
2193 NA
1457 https://secure.meetupstatic.com/photos/member/5/b/b/0/highres_185123472.jpeg
     response joined_rank visited_rank WrigleyDistance
1559 NA        965        2418         1867.88
352  NA        473        2027         1868.08
1488 NA       1192        2278         1868.08
2193 NA       2847         145         1868.13
1457 NA       1023         763         1868.13

     id        name
1398 111410472 Amit Meir
777   45985182 Xin Huang
1252  95387542 Aditya
1164  85906342 Shang Gao
1665 153705402 David Kreyenhagen
     bio
1398 NA
777  I am a senior research statistician in the Exploratory Statistics group in AbbVie Inc.
1252 NA
1164 NA
1665 NA
     link                                    lon     lat   city    state
1398 http://www.meetup.com/members/111410472 -122.29 47.63 Seattle WA
777  http://www.meetup.com/members/45985182  -122.29 47.66 Seattle WA
1252 http://www.meetup.com/members/95387542  -122.29 47.66 Seattle WA
1164 http://www.meetup.com/members/85906342  -122.29 47.66 Seattle WA
1665 http://www.meetup.com/members/153705402 -122.33 47.61 Seattle WA
     country visited             joined              status
1398 us      2016-05-23 16:24:25 2016-05-04 21:16:06 active
777  us      2016-05-30 18:28:34 2013-08-21 18:19:42 active
1252 us      2015-01-26 20:25:05 2015-01-26 20:25:05 active
1164 us      2013-08-08 16:59:39 2013-08-08 13:39:54 active
1665 us      2017-05-21 15:32:52 2016-09-14 14:34:26 active
     photo
1398 NA
777  https://secure.meetupstatic.com/photos/member/e/0/e/4/highres_51777572.jpeg
1252 https://secure.meetupstatic.com/photos/member/b/c/f/2/highres_243288370.jpeg
1164 NA
1665 https://secure.meetupstatic.com/photos/member/6/7/6/0/highres_249746464.jpeg
     response joined_rank visited_rank WrigleyDistance
1398 NA       1860        1652         1741.00
777  NA        793        1644         1741.01
1252 NA       1329        2173         1741.01
1164 NA        774        2539         1741.01
1665 NA       2050         969         1742.90

     id        name
1871 183838572 Andrew Olson
208    9931960 Aaron Rogers
1976 186530239 Aaron Katch
660   33342842 Mike Harwood
865   53962022 Charles Franklin
     bio
1871 NA
208  NA
1976 NA
660  Current Healthcare Statistician.  Previous experience as a bank Risk Manager (developing expected loss, application scoring, and behavioral scoring models), Warranty Supervisor (developing product diffusion, expected loss, and failure rate tools).
865  R, polls, visualization. Teach R for data and vis at Marquette and UW Madison.
     link                                    lon    lat   city      state
1871 http://www.meetup.com/members/183838572 -87.99 42.96 Milwaukee WI
208  http://www.meetup.com/members/9931960   -87.92 43.04 Milwaukee WI
1976 http://www.meetup.com/members/186530239 -87.92 43.04 Milwaukee WI
660  http://www.meetup.com/members/33342842  -87.92 43.04 Milwaukee WI
865  http://www.meetup.com/members/53962022  -87.92 43.04 Milwaukee WI
     country visited             joined              status
1871 us      2018-01-26 04:13:40 2017-07-10 07:19:06 active
208  us      2016-08-29 10:26:36 2015-10-28 09:32:36 active
1976 us      2016-05-14 00:32:08 2015-06-25 08:43:46 active
660  us      2014-02-15 11:28:54 2011-12-23 09:17:34 active
865  us      2013-10-25 20:29:29 2012-07-07 22:40:06 active
     photo
1871 https://secure.meetupstatic.com/photos/member/f/4/e/highres_243183918.jpeg
208  https://secure.meetupstatic.com/photos/member/4/c/f/c/highres_7699708.jpeg
1976 https://secure.meetupstatic.com/photos/member/7/8/6/2/highres_247350818.jpeg
660  NA
865  https://secure.meetupstatic.com/photos/member/d/c/6/6/highres_61676422.jpeg
     response joined_rank visited_rank WrigleyDistance
1871 yes      2503          44         72.12
208  NA       1673        1474         76.81
1976 NA       1527        1660         76.81
660  NA        218        2458         76.81
865  NA        384        2485         76.81

### Eapply

Using eapply we find the length of every object in current environment.

In [30]:
str(eapply(.GlobalEnv, length))

List of 10
 $ event_members   : int 8
 $ map_list        : int 2872
 $ paths           : int 15
 $ bylist          : int 311
 $ joinedyearcount : int 9
 $ event_members_df: int 7
 $ citycount       : int 311
 $ df              : int 17
 $ haversinef      : int 1
 $ dfList          : int 15

### Rapply

Using rapply, we find type of every object in one of the json Meetup API feeds which results in a listed nest object.

In [31]:
memberdata <- fromJSON("Meetup_JSON/CRUG_members5.json")

str(memberdata)

List of 2
 $ results:'data.frame':	200 obs. of  17 variables:
  ..$ country       : chr [1:200] "us" "us" "us" "us" ...
  ..$ city          : chr [1:200] "Chicago" "Chicago" "Chicago" "Chicago" ...
  ..$ topics        :List of 200
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	26 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:26] "big-data" "machine-learning" "data-analytics" "python" ...
  .. .. ..$ name  : chr [1:26] "Big Data" "Machine Learning" "Data Analytics" "Python" ...
  .. .. ..$ id    : int [1:26] 18062 29971 30928 1064 37381 38458 55324 102811 563 48471 ...
  .. ..$ :'data.frame':	9 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:9] "philosophy" "knowledge-sharing" "intellectual-discussion" "lgbtfriends" ...
  .. .. ..$ name  : chr [1:9] "Philosophy" "Knowledge Sharing" "Intellectual Discussion" "LGBT" ...
  .. .. ..$ id    : int [1:9] 849 65780 15083 10050 10454 74736 579 15046 3340
  .. ..$ :'data.frame':	13 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:13] "fitness" "yoga" "wine" "art" ...
  .. .. ..$ name  : chr [1:13] "Fitness" "Yoga" "Wine" "Art" ...
  .. .. ..$ id    : int [1:13] 242 244 611 1502 10280 10581 15123 17571 19741 26717 ...
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "business-strategy" "finance-and-wealth" "professional-networking" "investing" ...
  .. .. ..$ name  : chr [1:5] "Business Strategy" "Finance and Wealth" "Professional Networking" "Investing" ...
  .. .. ..$ id    : int [1:5] 17635 66789 15720 1307 34637
  .. ..$ :'data.frame':	12 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:12] "web" "mobile-technology" "user-experience" "big-data" ...
  .. .. ..$ name  : chr [1:12] "Web Technology" "Mobile Technology" "User Experience" "Big Data" ...
  .. .. ..$ id    : int [1:12] 10209 16216 19243 18062 15083 7789 154951 3880 638 16179 ...
  .. ..$ :'data.frame':	18 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:18] "environment" "sierraclub" "green" "conservation" ...
  .. .. ..$ name  : chr [1:18] "Environment" "Sierra Club" "Green Party" "Conservation" ...
  .. .. ..$ id    : int [1:18] 89 94 100 1700 1789 2479 2527 3135 4027 4417 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	1 obs. of  3 variables:
  .. .. ..$ urlkey: chr "business-analysts"
  .. .. ..$ name  : chr "Business Analysts"
  .. .. ..$ id    : int 37536
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "data-analytics" "data-visualization" "data-mining" "data-science" ...
  .. .. ..$ name  : chr [1:5] "Data Analytics" "Data Visualization" "Data Mining" "Data Science" ...
  .. .. ..$ id    : int [1:5] 30928 37381 55324 102811 110935
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	11 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:11] "chicago" "data-analytics" "predictive-analytics" "computer-programming" ...
  .. .. ..$ name  : chr [1:11] "Chicago" "Data Analytics" "Predictive Analytics" "Computer programming" ...
  .. .. ..$ id    : int [1:11] 1819 30928 38458 48471 55324 98380 102811 115913 17986 2516 ...
  .. ..$ :'data.frame':	13 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:13] "predictive-analytics" "computer-programming" "softwaredev" "professional-networking" ...
  .. .. ..$ name  : chr [1:13] "Predictive Analytics" "Computer programming" "Software Development" "Professional Networking" ...
  .. .. ..$ id    : int [1:13] 38458 48471 3833 15720 18167 85 88 29971 456 1064 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	20 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:20] "entrepreneurship" "startup-businesses" "lean-startup" "internet-startups" ...
  .. .. ..$ name  : chr [1:20] "Entrepreneurship" "Startup Businesses" "Lean Startup" "Internet Startups" ...
  .. .. ..$ id    : int [1:20] 19882 21681 38660 128595 18062 29971 30928 37381 38458 55324 ...
  .. ..$ :'data.frame':	25 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:25] "weightloss" "fitness" "biblestudy" "pickupsoccer" ...
  .. .. ..$ name  : chr [1:25] "Weight Loss" "Fitness" "Bible Study" "Pick-Up Soccer" ...
  .. .. ..$ id    : int [1:25] 240 242 2353 3340 3937 8652 15121 15231 17635 713 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	31 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:31] "java" "opensource" "softwaredev" "newtech" ...
  .. .. ..$ name  : chr [1:31] "Java" "Open Source" "Software Development" "New Technology" ...
  .. .. ..$ id    : int [1:31] 189 563 3833 9696 10538 10579 15167 15582 16216 18062 ...
  .. ..$ :'data.frame':	50 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:50] "nflfootball" "science" "animalwelfare" "musicians" ...
  .. .. ..$ name  : chr [1:50] "NFL Football" "Science" "Animal Welfare" "Musicians" ...
  .. .. ..$ id    : int [1:50] 57 85 92 173 223 242 382 407 408 411 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	39 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:39] "databasepro" "datamanagement" "businessintell" "hadoop" ...
  .. .. ..$ name  : chr [1:39] "Database Professionals" "Data Management" "Business Intelligence" "Hadoop" ...
  .. .. ..$ id    : int [1:39] 1245 10494 10538 18060 18062 30927 30928 37381 55324 126345 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	4 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:4] "big-data" "predictive-analytics" "technology-startups" "softwaredev"
  .. .. ..$ name  : chr [1:4] "Big Data" "Predictive Analytics" "Technology Startups" "Software Development"
  .. .. ..$ id    : int [1:4] 18062 38458 108403 3833
  .. ..$ :'data.frame':	1 obs. of  3 variables:
  .. .. ..$ urlkey: chr "data-science"
  .. .. ..$ name  : chr "Data Science"
  .. .. ..$ id    : int 102811
  .. ..$ :'data.frame':	12 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:12] "python" "chicago" "newtech" "data-analytics" ...
  .. .. ..$ name  : chr [1:12] "Python" "Chicago" "New Technology" "Data Analytics" ...
  .. .. ..$ id    : int [1:12] 1064 1819 9696 30928 48471 7029 15582 10553 1216152 39012 ...
  .. ..$ :'data.frame':	2 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:2] "data-analytics" "data-visualization"
  .. .. ..$ name  : chr [1:2] "Data Analytics" "Data Visualization"
  .. .. ..$ id    : int [1:2] 30928 37381
  .. ..$ :'data.frame':	50 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:50] "social-media" "web-development" "mobile-development" "software-craftsmanship" ...
  .. .. ..$ name  : chr [1:50] "Social Media" "Web Development" "Mobile Development" "Software Craftsmanship" ...
  .. .. ..$ id    : int [1:50] 15401 15582 21441 71692 78565 88843 563 659 3833 7029 ...
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "data-visualization" "predictive-analytics" "data-science" "big-data-analytics" ...
  .. .. ..$ name  : chr [1:5] "Data Visualization" "Predictive Analytics" "Data Science" "Big Data Analytics" ...
  .. .. ..$ id    : int [1:5] 37381 38458 102811 383411 7203
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "java" "fitness" "bookclub" "softwaredev" ...
  .. .. ..$ name  : chr [1:5] "Java" "Fitness" "Book Club" "Software Development" ...
  .. .. ..$ id    : int [1:5] 189 242 2767 3833 48471
  .. ..$ :'data.frame':	2 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:2] "businessintell" "predictive-analytics"
  .. .. ..$ name  : chr [1:2] "Business Intelligence" "Predictive Analytics"
  .. .. ..$ id    : int [1:2] 10538 38458
  .. ..$ :'data.frame':	10 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:10] "opensource" "newtech" "big-data" "machine-learning" ...
  .. .. ..$ name  : chr [1:10] "Open Source" "New Technology" "Big Data" "Machine Learning" ...
  .. .. ..$ id    : int [1:10] 563 9696 18062 29971 30928 37381 38458 55324 10538 98380
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "data-visualization" "computer-programming" "data-mining" "data-science" ...
  .. .. ..$ name  : chr [1:5] "Data Visualization" "Computer programming" "Data Mining" "Data Science" ...
  .. .. ..$ id    : int [1:5] 37381 48471 55324 102811 30928
  .. ..$ :'data.frame':	4 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:4] "computer-science" "machine-learning" "computer-programming" "data-mining"
  .. .. ..$ name  : chr [1:4] "Computer Science" "Machine Learning" "Computer programming" "Data Mining"
  .. .. ..$ id    : int [1:4] 21751 29971 48471 55324
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "tennis" "trail-running" "cycling" "data-science" ...
  .. .. ..$ name  : chr [1:5] "Tennis" "Trail Running" "Cycling" "Data Science" ...
  .. .. ..$ id    : int [1:5] 2926 16301 18617 102811 1481522
  .. ..$ :'data.frame':	39 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:39] "webdesign" "softwaredev" "edtech" "livemusic" ...
  .. .. ..$ name  : chr [1:39] "Web Design" "Software Development" "Education & Technology" "Live Music" ...
  .. .. ..$ id    : int [1:39] 659 3833 7203 8652 9696 10209 15018 15083 15582 15720 ...
  .. ..$ :'data.frame':	3 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:3] "machine-learning" "data-analytics" "data-visualization"
  .. .. ..$ name  : chr [1:3] "Machine Learning" "Data Analytics" "Data Visualization"
  .. .. ..$ id    : int [1:3] 29971 30928 37381
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	7 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:7] "businessintell" "predictive-analytics" "data-analytics" "r-project-for-statistical-computing" ...
  .. .. ..$ name  : chr [1:7] "Business Intelligence" "Predictive Analytics" "Data Analytics" "R Project for Statistical Computing" ...
  .. .. ..$ id    : int [1:7] 10538 38458 30928 98380 183 124860 124861
  .. ..$ :'data.frame':	14 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:14] "big-data" "data-analytics" "data-visualization" "open-data" ...
  .. .. ..$ name  : chr [1:14] "Big Data" "Data Analytics" "Data Visualization" "Open Data" ...
  .. .. ..$ id    : int [1:14] 18062 30928 37381 60043 118765 26477 122213 128666 29971 38458 ...
  .. ..$ :'data.frame':	1 obs. of  3 variables:
  .. .. ..$ urlkey: chr "shopping"
  .. .. ..$ name  : chr "Shopping"
  .. .. ..$ id    : int 9349
  .. ..$ :'data.frame':	4 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:4] "technology-startups" "business-strategy" "opensource" "businessintell"
  .. .. ..$ name  : chr [1:4] "Technology Startups" "Business Strategy" "Open Source" "Business Intelligence"
  .. .. ..$ id    : int [1:4] 108403 17635 563 10538
  .. ..$ :'data.frame':	5 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:5] "edtech" "opensource" "knowledge-sharing" "prodev" ...
  .. .. ..$ name  : chr [1:5] "Education & Technology" "Open Source" "Knowledge Sharing" "Professional Development" ...
  .. .. ..$ id    : int [1:5] 7203 563 65780 3880 18062
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	12 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:12] "prodev" "startup-businesses" "young-professionals" "concerts" ...
  .. .. ..$ name  : chr [1:12] "Professional Development" "Startup Businesses" "Young Professionals" "Concerts" ...
  .. .. ..$ id    : int [1:12] 3880 21681 15231 18909 173 15117 19195 48471 9696 3833 ...
  .. ..$ :'data.frame':	50 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:50] "german" "draw" "creative" "language" ...
  .. .. ..$ name  : chr [1:50] "German Language" "Drawing" "Creativity" "Language & Culture" ...
  .. .. ..$ id    : int [1:50] 644 20805 36229 10454 19146 933 10438 15046 16967 1162902 ...
  .. ..$ :'data.frame':	8 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:8] "big-data" "machine-learning" "data-analytics" "data-visualization" ...
  .. .. ..$ name  : chr [1:8] "Big Data" "Machine Learning" "Data Analytics" "Data Visualization" ...
  .. .. ..$ id    : int [1:8] 18062 29971 30928 37381 38458 48471 55324 102811
  .. ..$ :'data.frame':	8 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:8] "euchre" "drinking" "happy-hours" "womens-empowerment" ...
  .. .. ..$ name  : chr [1:8] "Euchre" "Drinking" "Happy Hour" "Women's Empowerment" ...
  .. .. ..$ id    : int [1:8] 554 15546 16800 17933 18528 19130 19146 19195
  .. ..$ :'data.frame':	19 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:19] "art" "figuredrawing" "livemusic" "creative-writing" ...
  .. .. ..$ name  : chr [1:19] "Art" "Figure Drawing" "Live Music" "Creative Writing" ...
  .. .. ..$ id    : int [1:19] 1502 2784 8652 15322 16728 713 1726 8867 10447 10475 ...
  .. ..$ :'data.frame':	11 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:11] "data-analytics" "predictive-analytics" "data-science" "bayesian-statistics" ...
  .. .. ..$ name  : chr [1:11] "Data Analytics" "Predictive Analytics" "Data Science" "Bayesian Statistics" ...
  .. .. ..$ id    : int [1:11] 30928 38458 102811 1103372 115913 17040 1452302 121498 29971 115768 ...
  .. ..$ :'data.frame':	8 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:8] "psychology" "science" "opensource" "big-data" ...
  .. .. ..$ name  : chr [1:8] "Psychology" "Science" "Open Source" "Big Data" ...
  .. .. ..$ id    : int [1:8] 3485 85 563 18062 48471 19243 10296 1245
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	10 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:10] "innovation" "running" "projectmgmt" "businessintell" ...
  .. .. ..$ name  : chr [1:10] "Innovation" "Running" "Project Management" "Business Intelligence" ...
  .. .. ..$ id    : int [1:10] 1954 2516 3438 10538 17635 18062 21681 30928 915 42206
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	17 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:17] "opensource" "technology" "hadoop" "machine-learning" ...
  .. .. ..$ name  : chr [1:17] "Open Source" "Technology" "Hadoop" "Machine Learning" ...
  .. .. ..$ id    : int [1:17] 563 10579 18060 29971 30928 37381 38458 98380 2906 1471442 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	13 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:13] "big-data" "machine-learning" "data-analytics" "predictive-analytics" ...
  .. .. ..$ name  : chr [1:13] "Big Data" "Machine Learning" "Data Analytics" "Predictive Analytics" ...
  .. .. ..$ id    : int [1:13] 18062 29971 30928 38458 55324 102811 456 9696 19882 20060 ...
  .. ..$ :'data.frame':	50 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:50] "ai" "robotics" "python" "investing" ...
  .. .. ..$ name  : chr [1:50] "Artificial Intelligence" "Robotics" "Python" "Investing" ...
  .. .. ..$ id    : int [1:50] 456 682 1064 1307 1731 3737 4455 6364 10357 10538 ...
  .. ..$ :'data.frame':	8 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:8] "big-data" "machine-learning" "data-analytics" "data-visualization" ...
  .. .. ..$ name  : chr [1:8] "Big Data" "Machine Learning" "Data Analytics" "Data Visualization" ...
  .. .. ..$ id    : int [1:8] 18062 29971 30928 37381 102811 383411 10579 108403
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	15 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:15] "opensource" "softwaredev" "newtech" "technology" ...
  .. .. ..$ name  : chr [1:15] "Open Source" "Software Development" "New Technology" "Technology" ...
  .. .. ..$ id    : int [1:15] 563 3833 9696 10579 15582 18062 19882 21681 29971 30928 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	28 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:28] "fitness" "hiking" "diningout" "travel" ...
  .. .. ..$ name  : chr [1:28] "Fitness" "Hiking" "Dining Out" "Travel" ...
  .. .. ..$ id    : int [1:28] 242 638 713 1998 8652 15046 15261 17201 17450 17571 ...
  .. ..$ :'data.frame':	46 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:46] "beer" "bike" "diy" "outdoor-adventures" ...
  .. .. ..$ name  : chr [1:46] "Beer" "Bicycling" "DIY (Do It Yourself)" "Outdoor Adventures" ...
  .. .. ..$ id    : int [1:46] 1475 579 10438 16967 713 1737 8652 3597 15117 18062 ...
  .. ..$ :'data.frame':	46 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:46] "esl" "poetry" "coffee" "scifi" ...
  .. .. ..$ name  : chr [1:46] "English as a Second Language" "Poetry" "Coffee" "Sci-Fi/Fantasy" ...
  .. .. ..$ id    : int [1:46] 182 222 235 317 713 781 1201 1819 1998 2773 ...
  .. ..$ :'data.frame':	16 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:16] "innovation" "self-improvement" "psychology" "publicspeaking" ...
  .. .. ..$ name  : chr [1:16] "Innovation" "Self-Improvement" "Psychology" "Public Speaking" ...
  .. .. ..$ id    : int [1:16] 1954 3336 3485 9300 15121 15167 16179 34160 15046 30928 ...
  .. ..$ :'data.frame':	12 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:12] "newtech" "automated-acceptance-testing" "simple-design-and-testing" "scrum" ...
  .. .. ..$ name  : chr [1:12] "New Technology" "Automated Acceptance Testing" "Simple Design and Testing" "Scrum" ...
  .. .. ..$ id    : int [1:12] 9696 643822 867532 10043 21549 21681 30996 122939 5938 25435 ...
  .. ..$ :'data.frame':	25 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:25] "chicago" "high-scalability-computing" "computer-programming" "high-performance-computing" ...
  .. .. ..$ name  : chr [1:25] "Chicago" "High Scalability Computing" "Computer programming" "High Performance Computing" ...
  .. .. ..$ id    : int [1:25] 1819 24410 48471 77687 77822 102226 136645 148578 148579 148580 ...
  .. ..$ :'data.frame':	37 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:37] "science" "scifi" "wine" "beer" ...
  .. .. ..$ name  : chr [1:37] "Science" "Sci-Fi/Fantasy" "Wine" "Beer" ...
  .. .. ..$ id    : int [1:37] 85 317 611 1475 9696 10538 15083 18062 21750 29158 ...
  .. ..$ :'data.frame':	7 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:7] "computer-science" "data-analytics" "r-project-for-statistical-computing" "applied-statistics" ...
  .. .. ..$ name  : chr [1:7] "Computer Science" "Data Analytics" "R Project for Statistical Computing" "Applied Statistics" ...
  .. .. ..$ id    : int [1:7] 21751 30928 98380 115913 18060 18061 18062
  .. ..$ :'data.frame':	21 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:21] "big-data" "data-analytics" "data-mining" "movies" ...
  .. .. ..$ name  : chr [1:21] "Big Data" "Data Analytics" "Data Mining" "Watching Movies" ...
  .. .. ..$ id    : int [1:21] 18062 30928 55324 1201 9760 17201 58259 15167 18060 27591 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	26 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:26] "machine-learning" "predictive-analytics" "data-science" "big-data" ...
  .. .. ..$ name  : chr [1:26] "Machine Learning" "Predictive Analytics" "Data Science" "Big Data" ...
  .. .. ..$ id    : int [1:26] 29971 38458 102811 18062 30928 563 9696 18060 21681 37381 ...
  .. ..$ :'data.frame':	50 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:50] "user-experience" "social-media-for-business" "innovation" "productdesign" ...
  .. .. ..$ name  : chr [1:50] "User Experience" "Social Media for Business" "Innovation" "Product Design" ...
  .. .. ..$ id    : int [1:50] 19243 37708 1954 2993 38660 62946 65025 135717 15616 18292 ...
  .. ..$ :'data.frame':	0 obs. of  0 variables
  .. ..$ :'data.frame':	2 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:2] "marketing" "businessintell"
  .. .. ..$ name  : chr [1:2] "Marketing" "Business Intelligence"
  .. .. ..$ id    : int [1:2] 1238 10538
  .. ..$ :'data.frame':	3 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:3] "bookclub" "live-theatre" "movies"
  .. .. ..$ name  : chr [1:3] "Book Club" "Theater" "Watching Movies"
  .. .. ..$ id    : int [1:3] 2767 23274 1201
  .. ..$ :'data.frame':	43 obs. of  3 variables:
  .. .. ..$ urlkey: chr [1:43] "fiction" "creative-writing" "authors" "writing" ...
  .. .. ..$ name  : chr [1:43] "Fiction" "Creative Writing" "Authors" "Writing" ...

In [32]:
memberdata_type <- rapply(memberdata, function(x) typeof(x), how="replace")
                         
str(memberdata_type)

List of 2
 $ results:List of 17
  ..$ country       : chr "character"
  ..$ city          : chr "character"
  ..$ topics        :List of 200
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ : Named list()
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. ..$ :List of 3
  .. .. ..$ urlkey: chr "character"
  .. .. ..$ name  : chr "character"
  .. .. ..$ id    : chr "integer"
  .. .. [list output truncated]
  ..$ joined        : chr "double"
  ..$ link          : chr "character"
  ..$ photo         :List of 6
  .. ..$ highres_link: chr "character"
  .. ..$ photo_id    : chr "integer"
  .. ..$ base_url    : chr "character"
  .. ..$ type        : chr "character"
  .. ..$ photo_link  : chr "character"
  .. ..$ thumb_link  : chr "character"
  ..$ lon           : chr "double"
  ..$ other_services:List of 5
  .. ..$ twitter :List of 1
  .. .. ..$ identifier: chr "character"
  .. ..$ linkedin:List of 1
  .. .. ..$ identifier: chr "character"
  .. ..$ facebook:List of 1
  .. .. ..$ identifier: chr "character"
  .. ..$ flickr  :List of 1
  .. .. ..$ identifier: chr "character"
  .. ..$ tumblr  :List of 1
  .. .. ..$ identifier: chr "character"
  ..$ name          : chr "character"
  ..$ visited       : chr "double"
  ..$ self          :List of 1
  .. ..$ common: Named list()
  ..$ id            : chr "integer"
  ..$ state         : chr "character"
  ..$ lat           : chr "double"
  ..$ status        : chr "character"
  ..$ bio           : chr "character"
  ..$ hometown      : chr "character"
 $ meta   :List of 12
  ..$ next       : chr "character"
  ..$ method     : chr "character"
  ..$ total_count: chr "integer"
  ..$ link       : chr "character"
  ..$ count      : chr "integer"
  ..$ description: chr "character"
  ..$ lon        : chr "character"
  ..$ title      : chr "character"
  ..$ url        : chr "character"
  ..$ id         : chr "character"
  ..$ updated    : chr "double"
  ..$ lat        : chr "character"